// Fetch comics
export const FETCH_COMICS_REQUEST = 'FETCH_COMICS_REQUEST';
export const FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS';
export const FETCH_COMICS_FAILURE = 'FETCH_COMICS_FAILURE';

// Fetch featured comics
export const FETCH_FEATURED_COMICS_REQUEST = 'FETCH_FEATURED_COMICS_REQUEST';
export const FETCH_FEATURED_COMICS_SUCCESS = 'FETCH_FEATURED_COMICS_SUCCESS';
export const FETCH_FEATURED_COMICS_FAILURE = 'FETCH_FEATURED_COMICS_FAILURE';

// Fetch comic of the month
export const FETCH_COMIC_OF_MONTH_REQUEST = 'FETCH_COMIC_OF_MONTH_REQUEST';
export const FETCH_COMIC_OF_MONTH_SUCCESS = 'FETCH_COMIC_OF_MONTH_SUCCESS';
export const FETCH_COMIC_OF_MONTH_FAILURE = 'FETCH_COMIC_OF_MONTH_FAILURE';

// Fetch moods
export const FETCH_COMIC_MOODS_REQUEST = 'FETCH_COMIC_MOODS_REQUEST';
export const FETCH_COMIC_MOODS_SUCCESS = 'FETCH_COMIC_MOODS_SUCCESS';
export const FETCH_COMIC_MOODS_FAILURE = 'FETCH_COMIC_MOODS_FAILURE';

// Fetch ages
export const FETCH_COMIC_AGES_REQUEST = 'FETCH_COMIC_AGES_REQUEST';
export const FETCH_COMIC_AGES_SUCCESS = 'FETCH_COMIC_AGES_SUCCESS';
export const FETCH_COMIC_AGES_FAILURE = 'FETCH_COMIC_AGES_FAILURE';

// Search comics
export const SEARCH_COMICS_REQUEST = 'SEARCH_COMICS_REQUEST';
export const SEARCH_COMICS_SUCCESS = 'SEARCH_COMICS_SUCCESS';
export const SEARCH_COMICS_FAILURE = 'SEARCH_COMICS_FAILURE';

// Fetch comic by slug
export const FETCH_COMIC_BY_SLUG_REQUEST = 'FETCH_COMIC_BY_SLUG_REQUEST';
export const FETCH_COMIC_BY_SLUG_SUCCESS = 'FETCH_COMIC_BY_SLUG_SUCCESS';
export const FETCH_COMIC_BY_SLUG_FAILURE = 'FETCH_COMIC_BY_SLUG_FAILURE'; 