// Fetch customer stories
export const FETCH_CUSTOMER_STORIES_REQUEST = 'FETCH_CUSTOMER_STORIES_REQUEST';
export const FETCH_CUSTOMER_STORIES_SUCCESS = 'FETCH_CUSTOMER_STORIES_SUCCESS';
export const FETCH_CUSTOMER_STORIES_FAILURE = 'FETCH_CUSTOMER_STORIES_FAILURE';

// Fetch featured customer stories
export const FETCH_FEATURED_CUSTOMER_STORIES_REQUEST = 'FETCH_FEATURED_CUSTOMER_STORIES_REQUEST';
export const FETCH_FEATURED_CUSTOMER_STORIES_SUCCESS = 'FETCH_FEATURED_CUSTOMER_STORIES_SUCCESS';
export const FETCH_FEATURED_CUSTOMER_STORIES_FAILURE = 'FETCH_FEATURED_CUSTOMER_STORIES_FAILURE';

// Fetch authors
export const FETCH_AUTHORS_REQUEST = 'FETCH_AUTHORS_REQUEST';
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE';

// Fetch customer stories by author
export const FETCH_CUSTOMER_STORIES_BY_AUTHOR_REQUEST = 'FETCH_CUSTOMER_STORIES_BY_AUTHOR_REQUEST';
export const FETCH_CUSTOMER_STORIES_BY_AUTHOR_SUCCESS = 'FETCH_CUSTOMER_STORIES_BY_AUTHOR_SUCCESS';
export const FETCH_CUSTOMER_STORIES_BY_AUTHOR_FAILURE = 'FETCH_CUSTOMER_STORIES_BY_AUTHOR_FAILURE';

// Search customer stories
export const SEARCH_CUSTOMER_STORIES_REQUEST = 'SEARCH_CUSTOMER_STORIES_REQUEST';
export const SEARCH_CUSTOMER_STORIES_SUCCESS = 'SEARCH_CUSTOMER_STORIES_SUCCESS';
export const SEARCH_CUSTOMER_STORIES_FAILURE = 'SEARCH_CUSTOMER_STORIES_FAILURE';

// Fetch customer story by slug
export const FETCH_CUSTOMER_STORY_BY_SLUG_REQUEST = 'FETCH_CUSTOMER_STORY_BY_SLUG_REQUEST';
export const FETCH_CUSTOMER_STORY_BY_SLUG_SUCCESS = 'FETCH_CUSTOMER_STORY_BY_SLUG_SUCCESS';
export const FETCH_CUSTOMER_STORY_BY_SLUG_FAILURE = 'FETCH_CUSTOMER_STORY_BY_SLUG_FAILURE'; 