// Fetch products
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

// Fetch featured products
export const FETCH_FEATURED_PRODUCTS_REQUEST = 'FETCH_FEATURED_PRODUCTS_REQUEST';
export const FETCH_FEATURED_PRODUCTS_SUCCESS = 'FETCH_FEATURED_PRODUCTS_SUCCESS';
export const FETCH_FEATURED_PRODUCTS_FAILURE = 'FETCH_FEATURED_PRODUCTS_FAILURE';

// Fetch combo products
export const FETCH_COMBO_PRODUCTS_REQUEST = 'FETCH_COMBO_PRODUCTS_REQUEST';
export const FETCH_COMBO_PRODUCTS_SUCCESS = 'FETCH_COMBO_PRODUCTS_SUCCESS';
export const FETCH_COMBO_PRODUCTS_FAILURE = 'FETCH_COMBO_PRODUCTS_FAILURE';

// Fetch trial pack
export const FETCH_TRIAL_PACK_REQUEST = 'FETCH_TRIAL_PACK_REQUEST';
export const FETCH_TRIAL_PACK_SUCCESS = 'FETCH_TRIAL_PACK_SUCCESS';
export const FETCH_TRIAL_PACK_FAILURE = 'FETCH_TRIAL_PACK_FAILURE';

// Search products
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';

// Fetch product by slug
export const FETCH_PRODUCT_BY_SLUG_REQUEST = 'FETCH_PRODUCT_BY_SLUG_REQUEST';
export const FETCH_PRODUCT_BY_SLUG_SUCCESS = 'FETCH_PRODUCT_BY_SLUG_SUCCESS';
export const FETCH_PRODUCT_BY_SLUG_FAILURE = 'FETCH_PRODUCT_BY_SLUG_FAILURE'; 