// Fetch audio stories
export const FETCH_AUDIO_STORIES_REQUEST = 'FETCH_AUDIO_STORIES_REQUEST';
export const FETCH_AUDIO_STORIES_SUCCESS = 'FETCH_AUDIO_STORIES_SUCCESS';
export const FETCH_AUDIO_STORIES_FAILURE = 'FETCH_AUDIO_STORIES_FAILURE';

// Fetch featured audio stories
export const FETCH_FEATURED_AUDIO_STORIES_REQUEST = 'FETCH_FEATURED_AUDIO_STORIES_REQUEST';
export const FETCH_FEATURED_AUDIO_STORIES_SUCCESS = 'FETCH_FEATURED_AUDIO_STORIES_SUCCESS';
export const FETCH_FEATURED_AUDIO_STORIES_FAILURE = 'FETCH_FEATURED_AUDIO_STORIES_FAILURE';

// Fetch narrators
export const FETCH_NARRATORS_REQUEST = 'FETCH_NARRATORS_REQUEST';
export const FETCH_NARRATORS_SUCCESS = 'FETCH_NARRATORS_SUCCESS';
export const FETCH_NARRATORS_FAILURE = 'FETCH_NARRATORS_FAILURE';

// Fetch audio story ages
export const FETCH_AUDIO_STORY_AGES_REQUEST = 'FETCH_AUDIO_STORY_AGES_REQUEST';
export const FETCH_AUDIO_STORY_AGES_SUCCESS = 'FETCH_AUDIO_STORY_AGES_SUCCESS';
export const FETCH_AUDIO_STORY_AGES_FAILURE = 'FETCH_AUDIO_STORY_AGES_FAILURE';

// Fetch audio stories by narrator
export const FETCH_AUDIO_STORIES_BY_NARRATOR_REQUEST = 'FETCH_AUDIO_STORIES_BY_NARRATOR_REQUEST';
export const FETCH_AUDIO_STORIES_BY_NARRATOR_SUCCESS = 'FETCH_AUDIO_STORIES_BY_NARRATOR_SUCCESS';
export const FETCH_AUDIO_STORIES_BY_NARRATOR_FAILURE = 'FETCH_AUDIO_STORIES_BY_NARRATOR_FAILURE';

// Search audio stories
export const SEARCH_AUDIO_STORIES_REQUEST = 'SEARCH_AUDIO_STORIES_REQUEST';
export const SEARCH_AUDIO_STORIES_SUCCESS = 'SEARCH_AUDIO_STORIES_SUCCESS';
export const SEARCH_AUDIO_STORIES_FAILURE = 'SEARCH_AUDIO_STORIES_FAILURE';

// Fetch audio story by slug
export const FETCH_AUDIO_STORY_BY_SLUG_REQUEST = 'FETCH_AUDIO_STORY_BY_SLUG_REQUEST';
export const FETCH_AUDIO_STORY_BY_SLUG_SUCCESS = 'FETCH_AUDIO_STORY_BY_SLUG_SUCCESS';
export const FETCH_AUDIO_STORY_BY_SLUG_FAILURE = 'FETCH_AUDIO_STORY_BY_SLUG_FAILURE'; 