// Competition Action Types

// Fetch all competitions
export const FETCH_COMPETITIONS_REQUEST = 'FETCH_COMPETITIONS_REQUEST';
export const FETCH_COMPETITIONS_SUCCESS = 'FETCH_COMPETITIONS_SUCCESS';
export const FETCH_COMPETITIONS_FAILURE = 'FETCH_COMPETITIONS_FAILURE';

// Fetch featured competitions
export const FETCH_FEATURED_COMPETITIONS_REQUEST = 'FETCH_FEATURED_COMPETITIONS_REQUEST';
export const FETCH_FEATURED_COMPETITIONS_SUCCESS = 'FETCH_FEATURED_COMPETITIONS_SUCCESS';
export const FETCH_FEATURED_COMPETITIONS_FAILURE = 'FETCH_FEATURED_COMPETITIONS_FAILURE';

// Fetch active competitions
export const FETCH_ACTIVE_COMPETITIONS_REQUEST = 'FETCH_ACTIVE_COMPETITIONS_REQUEST';
export const FETCH_ACTIVE_COMPETITIONS_SUCCESS = 'FETCH_ACTIVE_COMPETITIONS_SUCCESS';
export const FETCH_ACTIVE_COMPETITIONS_FAILURE = 'FETCH_ACTIVE_COMPETITIONS_FAILURE';

// Fetch upcoming competitions
export const FETCH_UPCOMING_COMPETITIONS_REQUEST = 'FETCH_UPCOMING_COMPETITIONS_REQUEST';
export const FETCH_UPCOMING_COMPETITIONS_SUCCESS = 'FETCH_UPCOMING_COMPETITIONS_SUCCESS';
export const FETCH_UPCOMING_COMPETITIONS_FAILURE = 'FETCH_UPCOMING_COMPETITIONS_FAILURE';

// Fetch competition by slug
export const FETCH_COMPETITION_BY_SLUG_REQUEST = 'FETCH_COMPETITION_BY_SLUG_REQUEST';
export const FETCH_COMPETITION_BY_SLUG_SUCCESS = 'FETCH_COMPETITION_BY_SLUG_SUCCESS';
export const FETCH_COMPETITION_BY_SLUG_FAILURE = 'FETCH_COMPETITION_BY_SLUG_FAILURE';

// Fetch competition statuses
export const FETCH_COMPETITION_STATUSES_REQUEST = 'FETCH_COMPETITION_STATUSES_REQUEST';
export const FETCH_COMPETITION_STATUSES_SUCCESS = 'FETCH_COMPETITION_STATUSES_SUCCESS';
export const FETCH_COMPETITION_STATUSES_FAILURE = 'FETCH_COMPETITION_STATUSES_FAILURE';

// Fetch competitions by status
export const FETCH_COMPETITIONS_BY_STATUS_REQUEST = 'FETCH_COMPETITIONS_BY_STATUS_REQUEST';
export const FETCH_COMPETITIONS_BY_STATUS_SUCCESS = 'FETCH_COMPETITIONS_BY_STATUS_SUCCESS';
export const FETCH_COMPETITIONS_BY_STATUS_FAILURE = 'FETCH_COMPETITIONS_BY_STATUS_FAILURE';

// Search competitions
export const SEARCH_COMPETITIONS_REQUEST = 'SEARCH_COMPETITIONS_REQUEST';
export const SEARCH_COMPETITIONS_SUCCESS = 'SEARCH_COMPETITIONS_SUCCESS';
export const SEARCH_COMPETITIONS_FAILURE = 'SEARCH_COMPETITIONS_FAILURE';

// Create competition
export const CREATE_COMPETITION_REQUEST = 'CREATE_COMPETITION_REQUEST';
export const CREATE_COMPETITION_SUCCESS = 'CREATE_COMPETITION_SUCCESS';
export const CREATE_COMPETITION_FAILURE = 'CREATE_COMPETITION_FAILURE';

// Update competition
export const UPDATE_COMPETITION_REQUEST = 'UPDATE_COMPETITION_REQUEST';
export const UPDATE_COMPETITION_SUCCESS = 'UPDATE_COMPETITION_SUCCESS';
export const UPDATE_COMPETITION_FAILURE = 'UPDATE_COMPETITION_FAILURE';

// Update participants
export const UPDATE_PARTICIPANTS_REQUEST = 'UPDATE_PARTICIPANTS_REQUEST';
export const UPDATE_PARTICIPANTS_SUCCESS = 'UPDATE_PARTICIPANTS_SUCCESS';
export const UPDATE_PARTICIPANTS_FAILURE = 'UPDATE_PARTICIPANTS_FAILURE';

// Delete competition
export const DELETE_COMPETITION_REQUEST = 'DELETE_COMPETITION_REQUEST';
export const DELETE_COMPETITION_SUCCESS = 'DELETE_COMPETITION_SUCCESS';
export const DELETE_COMPETITION_FAILURE = 'DELETE_COMPETITION_FAILURE'; 