// Fetch videos
export const FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';

// Fetch featured videos
export const FETCH_FEATURED_VIDEOS_REQUEST = 'FETCH_FEATURED_VIDEOS_REQUEST';
export const FETCH_FEATURED_VIDEOS_SUCCESS = 'FETCH_FEATURED_VIDEOS_SUCCESS';
export const FETCH_FEATURED_VIDEOS_FAILURE = 'FETCH_FEATURED_VIDEOS_FAILURE';

// Fetch presenters
export const FETCH_PRESENTERS_REQUEST = 'FETCH_PRESENTERS_REQUEST';
export const FETCH_PRESENTERS_SUCCESS = 'FETCH_PRESENTERS_SUCCESS';
export const FETCH_PRESENTERS_FAILURE = 'FETCH_PRESENTERS_FAILURE';

// Fetch video ages
export const FETCH_VIDEO_AGES_REQUEST = 'FETCH_VIDEO_AGES_REQUEST';
export const FETCH_VIDEO_AGES_SUCCESS = 'FETCH_VIDEO_AGES_SUCCESS';
export const FETCH_VIDEO_AGES_FAILURE = 'FETCH_VIDEO_AGES_FAILURE';

// Fetch videos by presenter
export const FETCH_VIDEOS_BY_PRESENTER_REQUEST = 'FETCH_VIDEOS_BY_PRESENTER_REQUEST';
export const FETCH_VIDEOS_BY_PRESENTER_SUCCESS = 'FETCH_VIDEOS_BY_PRESENTER_SUCCESS';
export const FETCH_VIDEOS_BY_PRESENTER_FAILURE = 'FETCH_VIDEOS_BY_PRESENTER_FAILURE';

// Fetch videos by duration
export const FETCH_VIDEOS_BY_DURATION_REQUEST = 'FETCH_VIDEOS_BY_DURATION_REQUEST';
export const FETCH_VIDEOS_BY_DURATION_SUCCESS = 'FETCH_VIDEOS_BY_DURATION_SUCCESS';
export const FETCH_VIDEOS_BY_DURATION_FAILURE = 'FETCH_VIDEOS_BY_DURATION_FAILURE';

// Search videos
export const SEARCH_VIDEOS_REQUEST = 'SEARCH_VIDEOS_REQUEST';
export const SEARCH_VIDEOS_SUCCESS = 'SEARCH_VIDEOS_SUCCESS';
export const SEARCH_VIDEOS_FAILURE = 'SEARCH_VIDEOS_FAILURE';

// Fetch video by slug
export const FETCH_VIDEO_BY_SLUG_REQUEST = 'FETCH_VIDEO_BY_SLUG_REQUEST';
export const FETCH_VIDEO_BY_SLUG_SUCCESS = 'FETCH_VIDEO_BY_SLUG_SUCCESS';
export const FETCH_VIDEO_BY_SLUG_FAILURE = 'FETCH_VIDEO_BY_SLUG_FAILURE'; 